# Generated by Django 5.1.4 on 2025-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userquizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
