# Generated by Django 5.1.4 on 2025-03-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizcategory_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='quizsubtopic',
            name='category',
        ),
        migrations.AddField(
            model_name='quizsubtopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.quiztopic'),
            preserve_default=False,
        ),
    ]
