# Generated by Django 5.1.4 on 2025-03-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quizsubtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizTopic',
        ),
        migrations.DeleteModel(
            name='QuizSubtopic',
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
