# Generated by Django 5.1.4 on 2025-03-27 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quizquestion_quizsubtopic_quiztopic_quizoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(default='A', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
    ]
