# Generated by Django 5.1.4 on 2025-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_text_quizquestion_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quizsubtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='userquizscore',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='userquizscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizTopic',
        ),
        migrations.DeleteModel(
            name='QuizSubtopic',
        ),
        migrations.DeleteModel(
            name='UserQuizScore',
        ),
    ]
